CREATE TABLE Currency (
    id int NOT NULL IDENTITY,
    code int NOT NULL,
    currency nvarchar(50) NOT NULL,
)
go


insert into Currency (code, currency) values(4,'Afghanistan Afghani')
insert into Currency (code, currency) values(8,'Albania Lek')
insert into Currency (code, currency) values(12,'Algerian Dinar')
insert into Currency (code, currency) values(973,'Angola Kwanza')
insert into Currency (code, currency) values(32,'Argentine Peso')
insert into Currency (code, currency) values(51,'Armenian Dram')
insert into Currency (code, currency) values(533,'Aruban Guilder')
insert into Currency (code, currency) values(36,'Australian Dollar')
insert into Currency (code, currency) values(31,'Azerbaijanian Manat')
insert into Currency (code, currency) values(44,'Bahamian Dollar')
insert into Currency (code, currency) values(48,'Bahraini Dinar')
insert into Currency (code, currency) values(50,'Bangladesh Taka')
insert into Currency (code, currency) values(52,'Barbados Dollar')
insert into Currency (code, currency) values(974,'Belarussian Ruble')
insert into Currency (code, currency) values(84,'Belize Dollar')
insert into Currency (code, currency) values(60,'Bermuda Dollar')
insert into Currency (code, currency) values(64,'Bhutan Ngultrum')
insert into Currency (code, currency) values(68,'Bolivia Boliviano')
insert into Currency (code, currency) values(72,'Botswana Pula')
insert into Currency (code, currency) values(986,'Brazilian Real')
insert into Currency (code, currency) values(96,'Brunei Dollar')
insert into Currency (code, currency) values(100,'Bulgarian Lev')
insert into Currency (code, currency) values(108,'Burundi Franc')
insert into Currency (code, currency) values(116,'Cambodia Riel')
insert into Currency (code, currency) values(124,'Canadian Dollar')
insert into Currency (code, currency) values(132,'Cape Verde Escudo')
insert into Currency (code, currency) values(136,'Cayman Islands Dollar')
insert into Currency (code, currency) values(952,'CFA Franc BCEAO')
insert into Currency (code, currency) values(950,'CFA Franc BEAC')
insert into Currency (code, currency) values(953,'CFP Franc')
insert into Currency (code, currency) values(152,'Chilean Peso')
insert into Currency (code, currency) values(170,'Colombian Peso')
insert into Currency (code, currency) values(174,'Comoro Franc')
insert into Currency (code, currency) values(977,'Convertible Marks')
insert into Currency (code, currency) values(188,'Costa Rican Colon')
insert into Currency (code, currency) values(191,'Croatian Kuna')
insert into Currency (code, currency) values(192,'Cuban Peso')
insert into Currency (code, currency) values(196,'Cyprus Pound')
insert into Currency (code, currency) values(203,'Czech Koruna')
insert into Currency (code, currency) values(208,'Danish Krone')
insert into Currency (code, currency) values(262,'Djibouti Franc')
insert into Currency (code, currency) values(214,'Dominican Peso')
insert into Currency (code, currency) values(951,'East Caribbean Dollar')
insert into Currency (code, currency) values(818,'Egyptian Pound')
insert into Currency (code, currency) values(222,'El Salvador Colon')
insert into Currency (code, currency) values(232,'Eritrea Nakfa')
insert into Currency (code, currency) values(233,'Estonia Kroon')
insert into Currency (code, currency) values(230,'Ethiopian Birr')
insert into Currency (code, currency) values(978,'Euro')
insert into Currency (code, currency) values(238,'Falkland Islands Pound')
insert into Currency (code, currency) values(242,'Fiji Dollar')
insert into Currency (code, currency) values(976,'Franc Congolais')
insert into Currency (code, currency) values(270,'Gambia Dalasi')
insert into Currency (code, currency) values(981,'Georgia Lari')
insert into Currency (code, currency) values(288,'Ghana Cedi')
insert into Currency (code, currency) values(292,'Gibraltar Pound')
insert into Currency (code, currency) values(320,'Guatemala Quetzal')
insert into Currency (code, currency) values(324,'Guinea Franc')
insert into Currency (code, currency) values(624,'Guinea-Bissau Peso')
insert into Currency (code, currency) values(328,'Guyana Dollar')
insert into Currency (code, currency) values(332,'Haiti Gourde')
insert into Currency (code, currency) values(340,'Honduras Lempira')
insert into Currency (code, currency) values(344,'Hong Kong Dollar')
insert into Currency (code, currency) values(348,'Hungary Forint')
insert into Currency (code, currency) values(352,'Iceland Krona')
insert into Currency (code, currency) values(356,'Indian Rupee')
insert into Currency (code, currency) values(360,'Indonesia Rupiah')
insert into Currency (code, currency) values(364,'Iranian Rial')
insert into Currency (code, currency) values(368,'Iraqi Dinar')
insert into Currency (code, currency) values(388,'Jamaican Dollar')
insert into Currency (code, currency) values(392,'Japan Yen')
insert into Currency (code, currency) values(400,'Jordanian Dinar')
insert into Currency (code, currency) values(398,'Kazakstan Tenge')
insert into Currency (code, currency) values(404,'Kenyan Shilling')
insert into Currency (code, currency) values(410,'Korea Won')
insert into Currency (code, currency) values(414,'Kuwaiti Dinar')
insert into Currency (code, currency) values(417,'Kyrgyzstan Som')
insert into Currency (code, currency) values(418,'Lao Kip')
insert into Currency (code, currency) values(428,'Latvian Lats')
insert into Currency (code, currency) values(422,'Lebanese Pound')
insert into Currency (code, currency) values(426,'Lesotho Loti')
insert into Currency (code, currency) values(430,'Liberian Dollar')
insert into Currency (code, currency) values(434,'Libyan Dinar')
insert into Currency (code, currency) values(440,'Lithuanian Litus')
insert into Currency (code, currency) values(446,'Macau Pataca')
insert into Currency (code, currency) values(807,'Macedonia Denar')
insert into Currency (code, currency) values(450,'Malagasy Franc')
insert into Currency (code, currency) values(454,'Malawi Kwacha')
insert into Currency (code, currency) values(458,'Malaysian Ringgit')
insert into Currency (code, currency) values(462,'Maldives Rufiyaa')
insert into Currency (code, currency) values(470,'Maltese Lira')
insert into Currency (code, currency) values(478,'Mauritania Ouguiya')
insert into Currency (code, currency) values(480,'Mauritius Rupee')
insert into Currency (code, currency) values(484,'Mexican Peso')
insert into Currency (code, currency) values(498,'Moldovan Leu')
insert into Currency (code, currency) values(496,'Mongolia Tugrik')
insert into Currency (code, currency) values(504,'Moroccan Dirham')
insert into Currency (code, currency) values(508,'Mozambique Metical')
insert into Currency (code, currency) values(104,'Myanmar Kyat')
insert into Currency (code, currency) values(516,'Namibia Dollar')
insert into Currency (code, currency) values(524,'Nepalese Rupee')
insert into Currency (code, currency) values(532,'Netherlands Antillian Guilder')
insert into Currency (code, currency) values(376,'New Israeli Sheqel')
insert into Currency (code, currency) values(554,'New Zealand Dollar')
insert into Currency (code, currency) values(558,'Nicaragua Cordoba Oro')
insert into Currency (code, currency) values(566,'Nigeria Naira')
insert into Currency (code, currency) values(408,'North Korean Won')
insert into Currency (code, currency) values(578,'Norwegian Krone')
insert into Currency (code, currency) values(586,'Pakistan Rupee')
insert into Currency (code, currency) values(590,'Panama Balboa')
insert into Currency (code, currency) values(598,'Papua New Guinea Kina')
insert into Currency (code, currency) values(600,'Paraguay Guarani')
insert into Currency (code, currency) values(604,'Peru Nuevo Sol')
insert into Currency (code, currency) values(858,'Peso Uruguayo')
insert into Currency (code, currency) values(608,'Philippine Peso')
insert into Currency (code, currency) values(985,'Poland Zloty')
insert into Currency (code, currency) values(634,'Qatari Rial')
insert into Currency (code, currency) values(512,'Rial Omani')
insert into Currency (code, currency) values(642,'Romania Leu')
insert into Currency (code, currency) values(643,'Russian Ruble')
insert into Currency (code, currency) values(646,'Rwanda Franc')
insert into Currency (code, currency) values(654,'Saint Helena Pound')
insert into Currency (code, currency) values(882,'Samoa Tala')
insert into Currency (code, currency) values(678,'S¦o Tome/Principe Dobra')
insert into Currency (code, currency) values(682,'Saudi Riyal')
insert into Currency (code, currency) values(690,'Seychelles Rupee')
insert into Currency (code, currency) values(694,'Sierra Leone Leone')
insert into Currency (code, currency) values(702,'Singapore Dollar')
insert into Currency (code, currency) values(703,'Slovak Koruna')
insert into Currency (code, currency) values(705,'Slovenia Tolar')
insert into Currency (code, currency) values(90,'Solomon Islands Dollar')
insert into Currency (code, currency) values(706,'Somali Shilling')
insert into Currency (code, currency) values(710,'South Africa Rand')
insert into Currency (code, currency) values(144,'Sri Lanka Rupee')
insert into Currency (code, currency) values(736,'Sudanese Dinar')
insert into Currency (code, currency) values(740,'Suriname Guilder')
insert into Currency (code, currency) values(748,'Swaziland Lilangeni')
insert into Currency (code, currency) values(752,'Swedish Krona')
insert into Currency (code, currency) values(756,'Swiss Franc')
insert into Currency (code, currency) values(760,'Syrian Pound')
insert into Currency (code, currency) values(901,'Taiwan Dollar')
insert into Currency (code, currency) values(972,'Tajikistan Somoni')
insert into Currency (code, currency) values(834,'Tanzanian Shilling')
insert into Currency (code, currency) values(764,'Thailand Baht')
insert into Currency (code, currency) values(626,'Timor Escudo')
insert into Currency (code, currency) values(776,'Tonga Pa''anga')
insert into Currency (code, currency) values(780,'Trinidad and Tobago Dollar')
insert into Currency (code, currency) values(788,'Tunisian Dinar')
insert into Currency (code, currency) values(792,'Turkish Lira')
insert into Currency (code, currency) values(795,'Turkmenistan Manat')
insert into Currency (code, currency) values(784,'UAE Dirham')
insert into Currency (code, currency) values(800,'Uganda Shilling')
insert into Currency (code, currency) values(826,'UK Pound Sterling')
insert into Currency (code, currency) values(980,'Ukraine Hryvnia')
insert into Currency (code, currency) values(840,'US Dollar')
insert into Currency (code, currency) values(860,'Uzbekistan Sum')
insert into Currency (code, currency) values(548,'Vanuatu Vatu')
insert into Currency (code, currency) values(862,'Venezuela Bolivar')
insert into Currency (code, currency) values(704,'Viet Nam Dong')
insert into Currency (code, currency) values(886,'Yemeni Rial')
insert into Currency (code, currency) values(156,'Yuan Renminbi')
insert into Currency (code, currency) values(891,'Yugoslavian Dinar')
insert into Currency (code, currency) values(894,'Zambia Kwacha')
insert into Currency (code, currency) values(716,'Zimbabwe Dollar')

select * from Currency
